import '../styles/globals.css'

import Head from 'next/head'
import { AnimatePresence } from "framer-motion";
import Navbar from './components/navbar';
import Hero from './components/Hero'
import Footer from './components/Footer';

const MyApp = ({ Component, pageProps }) => {


  return (
    <>
      <Head>
        <title>eeesshhmedia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className=' text-black min-h-screen '>

          <div className='bg-gradient-to-b from-[#5865F2] to-pink-200 '>
            <Navbar></Navbar>
            <Hero></Hero>
          </div>


          <div className='max-w-7xl mx-auto '>
          <AnimatePresence>
            <Component {...pageProps} />
            
          </AnimatePresence>
          </div>

          <div className='bg-gradient-to-b from-pink-300 to-[#5865F2] '>
            <Footer></Footer>
          </div>


        </div>

    </>
  )
}
export default MyApp